import type { FortniteChallenge } from '../types'

export type ChallengeDefinition = Omit<FortniteChallenge, 'id' | 'is_active' | 'created_at' | 'last_played_at'>

export const SOLO_CHALLENGES: ChallengeDefinition[] = [
  {
    name: 'Blood Bath',
    description: 'Get as many eliminations as possible.',
    format: 'solo',
    category: 'kill',
    time_limit_minutes: 5,
    win_condition: 'Most eliminations',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'First Blood Race',
    description: 'Race to get first elimination.',
    format: 'solo',
    category: 'kill',
    time_limit_minutes: 10,
    win_condition: 'Fastest first elimination',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Pistol Whip',
    description: 'Only use pistols.',
    format: 'solo',
    category: 'kill',
    time_limit_minutes: 5,
    win_condition: 'Pistol eliminations count',
    scoring_method: 'raw_count',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'One Shot',
    description: 'Sniper eliminations only.',
    format: 'solo',
    category: 'kill',
    time_limit_minutes: 5,
    win_condition: 'Most sniper eliminations',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Tourist Mode',
    description: 'Visit named locations.',
    format: 'solo',
    category: 'location',
    time_limit_minutes: 5,
    win_condition: 'Named locations visited',
    scoring_method: 'raw_count',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'The Grand Tour',
    description: 'Hit as many named locations.',
    format: 'solo',
    category: 'location',
    time_limit_minutes: 10,
    win_condition: 'Most named locations visited',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Summit',
    description: 'Reach highest point.',
    format: 'solo',
    category: 'location',
    time_limit_minutes: 5,
    win_condition: 'Reach the highest elevation point',
    scoring_method: 'binary',
    multiplier: null,
    binary_points: 4,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Loot Goblin',
    description: 'Open chests.',
    format: 'solo',
    category: 'loot',
    time_limit_minutes: 5,
    win_condition: 'Chests opened',
    scoring_method: 'raw_count',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Full Kit',
    description: 'Get full loadout: AR+shotgun+SMG+sniper+heals.',
    format: 'solo',
    category: 'loot',
    time_limit_minutes: 10,
    win_condition: 'Collect a complete loadout',
    scoring_method: 'binary',
    multiplier: null,
    binary_points: 4,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Shopping Spree',
    description: 'Spend gold at vending machines/NPCs.',
    format: 'solo',
    category: 'loot',
    time_limit_minutes: 5,
    win_condition: 'Most gold spent',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Cockroach',
    description: 'Survive as long as possible.',
    format: 'solo',
    category: 'survival',
    time_limit_minutes: 10,
    win_condition: 'Last alive or longest survival',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Pacifist Run',
    description: 'Survive without kills.',
    format: 'solo',
    category: 'survival',
    time_limit_minutes: 10,
    win_condition: 'Longest survival with zero eliminations',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Glass Cannon',
    description: 'Get elims but never heal.',
    format: 'solo',
    category: 'survival',
    time_limit_minutes: 10,
    win_condition: 'Eliminations without healing items',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Demolition Derby',
    description: 'Destroy structures/objects.',
    format: 'solo',
    category: 'stunt',
    time_limit_minutes: 5,
    win_condition: 'Structures/objects destroyed',
    scoring_method: 'raw_count',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Gone Fishin\'',
    description: 'Catch fish, each worth double.',
    format: 'solo',
    category: 'stunt',
    time_limit_minutes: 5,
    win_condition: 'Fish caught (each worth 2 points)',
    scoring_method: 'custom',
    multiplier: 2,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'The Floor is Lava',
    description: 'Stay off ground.',
    format: 'solo',
    category: 'stunt',
    time_limit_minutes: 3,
    win_condition: 'Longest time without touching ground',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Yeet',
    description: 'Launch yourself far.',
    format: 'solo',
    category: 'stunt',
    time_limit_minutes: 3,
    win_condition: 'Greatest distance from single launch',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Fists Only',
    description: 'Melee only, each kill worth triple.',
    format: 'solo',
    category: 'restriction',
    time_limit_minutes: 5,
    win_condition: 'Melee eliminations (each worth 3 points)',
    scoring_method: 'custom',
    multiplier: 3,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'No Build Zone',
    description: 'No building.',
    format: 'solo',
    category: 'restriction',
    time_limit_minutes: 5,
    win_condition: 'Eliminations with zero builds placed',
    scoring_method: 'raw_count',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Grounded',
    description: 'No vehicles/launch pads.',
    format: 'solo',
    category: 'restriction',
    time_limit_minutes: 5,
    win_condition: 'Eliminations using only ground movement',
    scoring_method: 'raw_count',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
]

export const SQUAD_CHALLENGES: ChallengeDefinition[] = [
  {
    name: 'MVP Race',
    description: 'Most elims on squad.',
    format: 'squad',
    category: 'kill',
    time_limit_minutes: null,
    win_condition: 'Most eliminations on the squad',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: 5,
    team_bonus_condition: 'Victory Royale',
  },
  {
    name: 'First Blood',
    description: 'First person to get an elimination.',
    format: 'squad',
    category: 'kill',
    time_limit_minutes: 10,
    win_condition: 'Fastest first elimination on squad',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Kill Steal',
    description: 'Get the most assists.',
    format: 'squad',
    category: 'kill',
    time_limit_minutes: null,
    win_condition: 'Most assists',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Glass Jaw',
    description: 'Most deaths loses.',
    format: 'squad',
    category: 'survival',
    time_limit_minutes: null,
    win_condition: 'Fewest deaths (enter death count)',
    scoring_method: 'inverse_ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: 3,
    team_bonus_condition: 'Top 5 finish',
  },
  {
    name: 'Hot Drop Survivor',
    description: 'Drop at hottest spot.',
    format: 'squad',
    category: 'survival',
    time_limit_minutes: null,
    win_condition: 'Longest survival after hot drop',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: 5,
    team_bonus_condition: 'Top 10 finish',
  },
  {
    name: 'Victory Lap',
    description: 'Win as squad, rank by elims.',
    format: 'squad',
    category: 'teamwork',
    time_limit_minutes: null,
    win_condition: 'Most eliminations in Victory Royale match',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: 8,
    team_bonus_condition: 'Victory Royale',
  },
  {
    name: 'Bodyguard',
    description: 'One player is VIP, protect them.',
    format: 'squad',
    category: 'teamwork',
    time_limit_minutes: null,
    win_condition: 'Most eliminations while protecting the VIP',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: 3,
    team_bonus_condition: 'VIP survives to top 5',
  },
  {
    name: 'No Callouts',
    description: 'No voice chat, pings only.',
    format: 'squad',
    category: 'teamwork',
    time_limit_minutes: null,
    win_condition: 'Most eliminations with pings-only communication',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: 5,
    team_bonus_condition: 'Victory Royale',
  },
  {
    name: 'Class System',
    description: 'Each player picks weapon class.',
    format: 'squad',
    category: 'restriction',
    time_limit_minutes: null,
    win_condition: 'Eliminations with assigned weapon class',
    scoring_method: 'custom',
    multiplier: 1,
    binary_points: null,
    team_bonus_points: 3,
    team_bonus_condition: 'Top 10 finish',
  },
  {
    name: 'Leftovers',
    description: 'Ground loot only.',
    format: 'squad',
    category: 'restriction',
    time_limit_minutes: null,
    win_condition: 'Most eliminations using ground loot only',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
  {
    name: 'Damage King',
    description: 'Deal most total damage.',
    format: 'squad',
    category: 'stunt',
    time_limit_minutes: null,
    win_condition: 'Most total damage dealt',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: 3,
    team_bonus_condition: '2000+ combined team damage',
  },
  {
    name: 'Hot Potato',
    description: 'Pass item between teammates.',
    format: 'squad',
    category: 'stunt',
    time_limit_minutes: null,
    win_condition: 'Most time NOT holding the hot potato item',
    scoring_method: 'ranked',
    multiplier: null,
    binary_points: null,
    team_bonus_points: null,
    team_bonus_condition: null,
  },
]

export const ALL_STARTER_CHALLENGES: ChallengeDefinition[] = [
  ...SOLO_CHALLENGES,
  ...SQUAD_CHALLENGES,
]
